// Code generated by protoc-gen-go.
// source: ws.proto
// DO NOT EDIT!

/*
Package wsRPC is a generated protocol buffer package.

It is generated from these files:
	ws.proto

It has these top-level messages:
	Ping
	Ack
	SpaceUpdate
	Setting
	NodeUpdate
	Addition
*/
package wsRPC

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ping struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ping) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Ack struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SpaceUpdate struct {
	SpaceUUID   string        `protobuf:"bytes,1,opt,name=spaceUUID" json:"spaceUUID,omitempty"`
	Frame       int64         `protobuf:"varint,2,opt,name=frame" json:"frame,omitempty"`
	ClientUUIDs []string      `protobuf:"bytes,3,rep,name=clientUUIDs" json:"clientUUIDs,omitempty"`
	NodeUpdates []*NodeUpdate `protobuf:"bytes,4,rep,name=nodeUpdates" json:"nodeUpdates,omitempty"`
	Additions   []*Addition   `protobuf:"bytes,5,rep,name=additions" json:"additions,omitempty"`
	Deletions   []int64       `protobuf:"varint,6,rep,packed,name=deletions" json:"deletions,omitempty"`
}

func (m *SpaceUpdate) Reset()                    { *m = SpaceUpdate{} }
func (m *SpaceUpdate) String() string            { return proto.CompactTextString(m) }
func (*SpaceUpdate) ProtoMessage()               {}
func (*SpaceUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SpaceUpdate) GetSpaceUUID() string {
	if m != nil {
		return m.SpaceUUID
	}
	return ""
}

func (m *SpaceUpdate) GetFrame() int64 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *SpaceUpdate) GetClientUUIDs() []string {
	if m != nil {
		return m.ClientUUIDs
	}
	return nil
}

func (m *SpaceUpdate) GetNodeUpdates() []*NodeUpdate {
	if m != nil {
		return m.NodeUpdates
	}
	return nil
}

func (m *SpaceUpdate) GetAdditions() []*Addition {
	if m != nil {
		return m.Additions
	}
	return nil
}

func (m *SpaceUpdate) GetDeletions() []int64 {
	if m != nil {
		return m.Deletions
	}
	return nil
}

type Setting struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Setting) Reset()                    { *m = Setting{} }
func (m *Setting) String() string            { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()               {}
func (*Setting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Setting) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Setting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type NodeUpdate struct {
	Id           int64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Settings     []*Setting `protobuf:"bytes,2,rep,name=settings" json:"settings,omitempty"`
	Position     []float64  `protobuf:"fixed64,3,rep,packed,name=position" json:"position,omitempty"`
	Orientation  []float64  `protobuf:"fixed64,4,rep,packed,name=orientation" json:"orientation,omitempty"`
	Translation  []float64  `protobuf:"fixed64,5,rep,packed,name=translation" json:"translation,omitempty"`
	Rotation     []float64  `protobuf:"fixed64,6,rep,packed,name=rotation" json:"rotation,omitempty"`
	Scale        []float64  `protobuf:"fixed64,7,rep,packed,name=scale" json:"scale,omitempty"`
	TemplateUUID string     `protobuf:"bytes,8,opt,name=templateUUID" json:"templateUUID,omitempty"`
}

func (m *NodeUpdate) Reset()                    { *m = NodeUpdate{} }
func (m *NodeUpdate) String() string            { return proto.CompactTextString(m) }
func (*NodeUpdate) ProtoMessage()               {}
func (*NodeUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NodeUpdate) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeUpdate) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *NodeUpdate) GetPosition() []float64 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *NodeUpdate) GetOrientation() []float64 {
	if m != nil {
		return m.Orientation
	}
	return nil
}

func (m *NodeUpdate) GetTranslation() []float64 {
	if m != nil {
		return m.Translation
	}
	return nil
}

func (m *NodeUpdate) GetRotation() []float64 {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *NodeUpdate) GetScale() []float64 {
	if m != nil {
		return m.Scale
	}
	return nil
}

func (m *NodeUpdate) GetTemplateUUID() string {
	if m != nil {
		return m.TemplateUUID
	}
	return ""
}

type Addition struct {
	Id           int64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Settings     []*Setting `protobuf:"bytes,2,rep,name=settings" json:"settings,omitempty"`
	Position     []float64  `protobuf:"fixed64,3,rep,packed,name=position" json:"position,omitempty"`
	Orientation  []float64  `protobuf:"fixed64,4,rep,packed,name=orientation" json:"orientation,omitempty"`
	Translation  []float64  `protobuf:"fixed64,5,rep,packed,name=translation" json:"translation,omitempty"`
	Rotation     []float64  `protobuf:"fixed64,6,rep,packed,name=rotation" json:"rotation,omitempty"`
	Scale        []float64  `protobuf:"fixed64,7,rep,packed,name=scale" json:"scale,omitempty"`
	Parent       int64      `protobuf:"varint,8,opt,name=parent" json:"parent,omitempty"`
	TemplateUUID string     `protobuf:"bytes,9,opt,name=templateUUID" json:"templateUUID,omitempty"`
}

func (m *Addition) Reset()                    { *m = Addition{} }
func (m *Addition) String() string            { return proto.CompactTextString(m) }
func (*Addition) ProtoMessage()               {}
func (*Addition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Addition) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Addition) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *Addition) GetPosition() []float64 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Addition) GetOrientation() []float64 {
	if m != nil {
		return m.Orientation
	}
	return nil
}

func (m *Addition) GetTranslation() []float64 {
	if m != nil {
		return m.Translation
	}
	return nil
}

func (m *Addition) GetRotation() []float64 {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Addition) GetScale() []float64 {
	if m != nil {
		return m.Scale
	}
	return nil
}

func (m *Addition) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Addition) GetTemplateUUID() string {
	if m != nil {
		return m.TemplateUUID
	}
	return ""
}

func init() {
	proto.RegisterType((*Ping)(nil), "wsRPC.Ping")
	proto.RegisterType((*Ack)(nil), "wsRPC.Ack")
	proto.RegisterType((*SpaceUpdate)(nil), "wsRPC.SpaceUpdate")
	proto.RegisterType((*Setting)(nil), "wsRPC.Setting")
	proto.RegisterType((*NodeUpdate)(nil), "wsRPC.NodeUpdate")
	proto.RegisterType((*Addition)(nil), "wsRPC.Addition")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WSHost service

type WSHostClient interface {
	// Test whether a sim host is responsive
	HandlePing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Ack, error)
	// Send space updates to WS clients
	SendSpaceUpdate(ctx context.Context, in *SpaceUpdate, opts ...grpc.CallOption) (*Ack, error)
}

type wSHostClient struct {
	cc *grpc.ClientConn
}

func NewWSHostClient(cc *grpc.ClientConn) WSHostClient {
	return &wSHostClient{cc}
}

func (c *wSHostClient) HandlePing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := grpc.Invoke(ctx, "/wsRPC.WSHost/HandlePing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wSHostClient) SendSpaceUpdate(ctx context.Context, in *SpaceUpdate, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := grpc.Invoke(ctx, "/wsRPC.WSHost/SendSpaceUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WSHost service

type WSHostServer interface {
	// Test whether a sim host is responsive
	HandlePing(context.Context, *Ping) (*Ack, error)
	// Send space updates to WS clients
	SendSpaceUpdate(context.Context, *SpaceUpdate) (*Ack, error)
}

func RegisterWSHostServer(s *grpc.Server, srv WSHostServer) {
	s.RegisterService(&_WSHost_serviceDesc, srv)
}

func _WSHost_HandlePing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WSHostServer).HandlePing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wsRPC.WSHost/HandlePing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WSHostServer).HandlePing(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _WSHost_SendSpaceUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpaceUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WSHostServer).SendSpaceUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wsRPC.WSHost/SendSpaceUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WSHostServer).SendSpaceUpdate(ctx, req.(*SpaceUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

var _WSHost_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wsRPC.WSHost",
	HandlerType: (*WSHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandlePing",
			Handler:    _WSHost_HandlePing_Handler,
		},
		{
			MethodName: "SendSpaceUpdate",
			Handler:    _WSHost_SendSpaceUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ws.proto",
}

func init() { proto.RegisterFile("ws.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xdc, 0x53, 0xdd, 0x8a, 0xd4, 0x30,
	0x14, 0xb6, 0xcd, 0x4c, 0xa7, 0x3d, 0x95, 0x5d, 0x3d, 0x88, 0x94, 0x41, 0xb0, 0xf4, 0xc6, 0x22,
	0x38, 0xe0, 0xce, 0x13, 0x2c, 0x7a, 0xb1, 0xde, 0xc8, 0x92, 0xb2, 0x78, 0x1d, 0x9b, 0xec, 0x52,
	0xa6, 0x93, 0x94, 0x26, 0xba, 0xf8, 0x1e, 0xbe, 0xa2, 0xaf, 0x21, 0x92, 0x9f, 0x4e, 0xbb, 0xcc,
	0x1b, 0x78, 0x97, 0xef, 0x3b, 0xdf, 0x39, 0x39, 0xdf, 0xd7, 0x06, 0xd2, 0x47, 0xbd, 0x1b, 0x46,
	0x65, 0x14, 0xae, 0x1f, 0x35, 0xbd, 0xfd, 0x54, 0x6d, 0x61, 0x75, 0xdb, 0xc9, 0x07, 0x44, 0x58,
	0x49, 0x76, 0x14, 0x45, 0x54, 0x46, 0x75, 0x46, 0xdd, 0xb9, 0x7a, 0x0b, 0xe4, 0xba, 0x3d, 0x60,
	0x01, 0x9b, 0xa3, 0xd0, 0x9a, 0x3d, 0x4c, 0xd5, 0x09, 0x56, 0x7f, 0x22, 0xc8, 0x9b, 0x81, 0xb5,
	0xe2, 0x6e, 0xe0, 0xcc, 0x08, 0x7c, 0x03, 0x99, 0x76, 0xf0, 0xee, 0xcb, 0xe7, 0xa0, 0x9d, 0x09,
	0x7c, 0x05, 0xeb, 0xfb, 0xd1, 0xde, 0x11, 0x97, 0x51, 0x4d, 0xa8, 0x07, 0x58, 0x42, 0xde, 0xf6,
	0x9d, 0x90, 0xc6, 0x6a, 0x74, 0x41, 0x4a, 0x52, 0x67, 0x74, 0x49, 0xe1, 0x1e, 0x72, 0xa9, 0x78,
	0xb8, 0x43, 0x17, 0xab, 0x92, 0xd4, 0xf9, 0xd5, 0xcb, 0x9d, 0xdb, 0x7f, 0xf7, 0xf5, 0x54, 0xa1,
	0x4b, 0x15, 0x7e, 0x80, 0x8c, 0x71, 0xde, 0x99, 0x4e, 0x49, 0x5d, 0xac, 0x5d, 0xcb, 0x65, 0x68,
	0xb9, 0x0e, 0x3c, 0x9d, 0x15, 0x76, 0x73, 0x2e, 0x7a, 0xe1, 0xe5, 0x49, 0x49, 0x6a, 0x42, 0x67,
	0xa2, 0xfa, 0x08, 0x9b, 0x46, 0x18, 0x63, 0x73, 0x7a, 0x01, 0xe4, 0x20, 0x7e, 0x05, 0x73, 0xf6,
	0x68, 0x6d, 0xfd, 0x64, 0xfd, 0x0f, 0x6f, 0x2b, 0xa3, 0x1e, 0x54, 0x7f, 0x23, 0x80, 0x79, 0x37,
	0xbc, 0x80, 0xb8, 0xe3, 0xae, 0x8b, 0xd0, 0xb8, 0xe3, 0xf8, 0x1e, 0x52, 0xed, 0x27, 0xea, 0x22,
	0x76, 0xdb, 0x5d, 0x84, 0xed, 0xc2, 0x45, 0xf4, 0x54, 0xc7, 0x2d, 0xa4, 0x83, 0xd2, 0x6e, 0x51,
	0x17, 0x4f, 0x44, 0x4f, 0xd8, 0xa6, 0xa7, 0x46, 0x1b, 0x15, 0x73, 0xe5, 0x95, 0x2b, 0x2f, 0x29,
	0xab, 0x30, 0x23, 0x93, 0xba, 0xf7, 0x8a, 0xb5, 0x57, 0x2c, 0x28, 0x3b, 0x7f, 0x54, 0x61, 0x40,
	0xe2, 0xe7, 0x4f, 0xd8, 0x9a, 0xd3, 0x2d, 0xeb, 0x45, 0xb1, 0x71, 0x05, 0x0f, 0xb0, 0x82, 0xe7,
	0x46, 0x1c, 0x87, 0x9e, 0x19, 0xff, 0xa9, 0x53, 0xe7, 0xfc, 0x09, 0x57, 0xfd, 0x8e, 0x21, 0x9d,
	0x92, 0xfe, 0xcf, 0xec, 0xbf, 0x86, 0x64, 0x60, 0xa3, 0x90, 0xc6, 0x19, 0x27, 0x34, 0xa0, 0xb3,
	0x58, 0xb2, 0xf3, 0x58, 0xae, 0xee, 0x21, 0xf9, 0xd6, 0xdc, 0x28, 0x6d, 0xf0, 0x1d, 0xc0, 0x0d,
	0x93, 0xbc, 0x17, 0xee, 0xfd, 0xe5, 0xc1, 0xbf, 0x05, 0x5b, 0x98, 0xfe, 0xd4, 0xf6, 0x50, 0x3d,
	0xc3, 0x3d, 0x5c, 0x36, 0x42, 0xf2, 0xe5, 0x43, 0xc3, 0x29, 0xad, 0x99, 0x7b, 0xda, 0xf4, 0x3d,
	0x71, 0xaf, 0x7c, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x92, 0x62, 0xec, 0xf1, 0x03, 0x00,
	0x00,
}
