// Code generated by protoc-gen-go.
// source: sim.proto
// DO NOT EDIT!

/*
Package sim is a generated protocol buffer package.

It is generated from these files:
	sim.proto

It has these top-level messages:
	ListSimInfosParams
	SimInfo
	SimInfoList
	Ping
	Ack
*/
package sim

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListSimInfosParams struct {
}

func (m *ListSimInfosParams) Reset()                    { *m = ListSimInfosParams{} }
func (m *ListSimInfosParams) String() string            { return proto.CompactTextString(m) }
func (*ListSimInfosParams) ProtoMessage()               {}
func (*ListSimInfosParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SimInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Uuid string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *SimInfo) Reset()                    { *m = SimInfo{} }
func (m *SimInfo) String() string            { return proto.CompactTextString(m) }
func (*SimInfo) ProtoMessage()               {}
func (*SimInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SimInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SimInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type SimInfoList struct {
	Infos []*SimInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
}

func (m *SimInfoList) Reset()                    { *m = SimInfoList{} }
func (m *SimInfoList) String() string            { return proto.CompactTextString(m) }
func (*SimInfoList) ProtoMessage()               {}
func (*SimInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SimInfoList) GetInfos() []*SimInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type Ping struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Ping) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Ack struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ListSimInfosParams)(nil), "sim.ListSimInfosParams")
	proto.RegisterType((*SimInfo)(nil), "sim.SimInfo")
	proto.RegisterType((*SimInfoList)(nil), "sim.SimInfoList")
	proto.RegisterType((*Ping)(nil), "sim.Ping")
	proto.RegisterType((*Ack)(nil), "sim.Ack")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SimHost service

type SimHostClient interface {
	SendPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Ack, error)
	ListSimInfos(ctx context.Context, in *ListSimInfosParams, opts ...grpc.CallOption) (*SimInfoList, error)
}

type simHostClient struct {
	cc *grpc.ClientConn
}

func NewSimHostClient(cc *grpc.ClientConn) SimHostClient {
	return &simHostClient{cc}
}

func (c *simHostClient) SendPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := grpc.Invoke(ctx, "/sim.SimHost/SendPing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simHostClient) ListSimInfos(ctx context.Context, in *ListSimInfosParams, opts ...grpc.CallOption) (*SimInfoList, error) {
	out := new(SimInfoList)
	err := grpc.Invoke(ctx, "/sim.SimHost/ListSimInfos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SimHost service

type SimHostServer interface {
	SendPing(context.Context, *Ping) (*Ack, error)
	ListSimInfos(context.Context, *ListSimInfosParams) (*SimInfoList, error)
}

func RegisterSimHostServer(s *grpc.Server, srv SimHostServer) {
	s.RegisterService(&_SimHost_serviceDesc, srv)
}

func _SimHost_SendPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimHostServer).SendPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sim.SimHost/SendPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimHostServer).SendPing(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimHost_ListSimInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSimInfosParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimHostServer).ListSimInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sim.SimHost/ListSimInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimHostServer).ListSimInfos(ctx, req.(*ListSimInfosParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimHost_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sim.SimHost",
	HandlerType: (*SimHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPing",
			Handler:    _SimHost_SendPing_Handler,
		},
		{
			MethodName: "ListSimInfos",
			Handler:    _SimHost_ListSimInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sim.proto",
}

func init() { proto.RegisterFile("sim.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0xce, 0xcc, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0xce, 0xcc, 0x55, 0x12, 0xe1, 0x12, 0xf2, 0xc9,
	0x2c, 0x2e, 0x09, 0xce, 0xcc, 0xf5, 0xcc, 0x4b, 0xcb, 0x2f, 0x0e, 0x48, 0x2c, 0x4a, 0xcc, 0x2d,
	0x56, 0x32, 0xe4, 0x62, 0x87, 0x8a, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0xd2, 0xd2, 0xcc, 0x14, 0x09, 0x26, 0x88,
	0x18, 0x88, 0xad, 0x64, 0xc8, 0xc5, 0x0d, 0xd5, 0x02, 0x32, 0x4f, 0x48, 0x89, 0x8b, 0x35, 0x13,
	0x64, 0xa0, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0x8f, 0x1e, 0xc8, 0x5e, 0xa8, 0x82, 0x20,
	0x88, 0x94, 0x92, 0x14, 0x17, 0x4b, 0x40, 0x66, 0x5e, 0x3a, 0x36, 0x2b, 0x94, 0xe4, 0xb9, 0x98,
	0x1d, 0x93, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x61, 0xb2, 0x30,
	0xae, 0x51, 0x26, 0xd8, 0x89, 0x1e, 0xf9, 0xc5, 0x25, 0x42, 0x8a, 0x5c, 0x1c, 0xc1, 0xa9, 0x79,
	0x29, 0x60, 0xb3, 0x38, 0xc1, 0x16, 0x81, 0x98, 0x52, 0x1c, 0x60, 0xa6, 0x63, 0x72, 0xb6, 0x12,
	0x83, 0x90, 0x35, 0x17, 0x0f, 0xb2, 0x37, 0x85, 0xc4, 0xc1, 0x72, 0x98, 0x3e, 0x97, 0x12, 0x40,
	0x76, 0x28, 0x48, 0x5e, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0x5e, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd2, 0xda, 0x85, 0x13, 0x3c, 0x01, 0x00, 0x00,
}
